version: '2'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - .:/var/lib/redis/data
  db:
    image: postgres:9.4.5
    volumes:
      - .:/usr/local/pgsql/data
  elasticsearch:
    image: elasticsearch:5.5
    volumes:
      - .:/usr/share/elasticsearch/data
  jobs:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/forli
    depends_on:
      - db
      - redis
      - elasticsearch
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/Forli
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elasticsearch
  # ember:
  #   build: .
  #   command: ember serve
  #   volumes:
  #     - .:/forli/ember