defaults: &defaults
  url: 'redis://localhost:6379'
  namespace: 'forli_redis'
  timeout: 5

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  url: <%= ENV['REDIS_URL'] %>