default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: forli_development

test:
  <<: *default
  database: forli_test

production:
  <<: *default
  database: forli_production
  username: forli
  password: <%= ENV['FORLI_DATABASE_PASSWORD'] %>