defaults: &defaults
  :url: 'redis://localhost:6379'
  :verbose: true
  :logfile: ./log/sidekiq.log
  :timeout: 30
  :queues:
    - [notification]
    - [vote_dump]
    - [spam_check]
    - [search_indexer]

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  url: <%= ENV['REDIS_URL'] %>