defaults: &defaults
  :url: 'redis://localhost:6379'
  :verbose: true
  :concurrency: 25
  :timeout: 30
  :queues:
    - [notification]
    - [vote_dump]
    - [spam_check]
    - [search_indexer]

development:
  <<: *defaults
  :logfile: log/sidekiq.log

staging:
  <<: *defaults

production:
  <<: *defaults
  :url: <%= ENV['REDIS_URL'] %>
  :concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] %>